### ISSUE TITLE
Process hangs when calling directory with empty match_template

### ISSUE THREAD

**Issue by jmoon1506** [IBM/data-broker#130]
```
from dbr_module import dbr
from _dbr_interface import ffi

dbr_hdl = dbr.create("dummy_namespace", dbr.DBR_PERST_VOLATILE_SIMPLE, ffi.new('DBR_GroupList_t'))

dbr.put(dbr_hdl, 100, 'dummy_key_1', dbr.DBR_GROUP_EMPTY)

# OKAY
keys, nKeys, res = dbr.directory(dbr_hdl, 'dummy_key_*', dbr.DBR_GROUP_EMPTY, 1000, 1000)
print(keys)

# HANGS FOREVER
keys, nKeys, res = dbr.directory(dbr_hdl, 'not_dummy_key_*', dbr.DBR_GROUP_EMPTY, 1000, 1000)
print(keys)
```

When using the python binding's directory function, Databroker hangs silently if the match_template doesn't match any keys.

**Comment by jmoon1506** [comment]
Link to python API:

[https://github.com/IBM/data-broker/tree/master/bindings/python](https://github.com/IBM/data-broker/tree/master/bindings/python)

**Comment by Sara-KS** [comment]
Hi @jmoon1506,

What is the behavior if you call the dbr.testKey function with an empty match_template prior to trying the directory function? If the key does not exist, then you can skip the directory call or wait and try again later.

**Comment by jmoon1506** [comment]
That seems to work, but in order to use a match_template we check an iterator instead of testKey.

```
first_key, iterator = dbr.iterator(dbr_hdl, dbr.DBR_ITERATOR_NEW, dbr.DBR_GROUP_EMPTY, match_template)
if first_key != None:
    keys, nKeys, res = dbr.directory(dbr_hdl, match_template, dbr.DBR_GROUP_EMPTY, count, 1000)
```

**Comment by lasch** [comment]
@jmoon1506 I think, I found and fixed the issue. Do you need a tagged version in order to test it on your side? Otherwise, I'd wait for you to confirm it's fixed and then would tag this update version.

**Comment by jmoon1506** [comment]
Hi @lasch. Sorry for the delay -- I have tested the latest master commit's python bindings, and it works correctly. Please go ahead and tag this updated version.

**Comment by lasch** [comment]
Thanks @jmoon1506 . New version is tagged as version: 0.7.2
