### ISSUE TITLE
Cluster mode deletion test takes a lot of time

### ISSUE THREAD

**Issue by lasch** [IBM/data-broker#14]
During tests with cluster mode Redis, I noticed the test_dbrDelete takes a lot of time (~800s).

After taking a closer look it turns out that the scan command (on phase of the delete processing) constantly runs into connection timeout events and thus taking 1s breaks from processing.

**Comment by damora** [comment]
so it is losing the socket connection and fails and then has to retry at 1s intervals?

**Comment by lasch** [comment]
No. I should have called it receive timeout of 1s.
Libevent activates the connection and then the buggy code was skipping to the next active in some cases. So there was a connection with pending data that didn't get processed. I.e. the corresponding command could not complete until libevent would activate that connection again (this time with a timeout event)
There are no disconnect/reconnect actions involved.

**Comment by lasch** [comment]
fixed.
